steps:
- name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  entrypoint: 'dotnet'
  args: ['restore']

- name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  entrypoint: 'dotnet'
  args: ['publish', '-c', 'Release', '-o', 'publish']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'publish/app.yaml']

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY
