steps:
- name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  entrypoint: 'dotnet'
  args: ['publish', '-c', 'Release', '-o', './publish']

# New step to copy app.yaml into the publish directory
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', 'cp ./app.yaml ./publish/app.yaml']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', './publish/app.yaml']

timeout: '1600s'  # Adjust this timeout based on your expected build time

options:
  logging: CLOUD_LOGGING_ONLY
